mendersoftware/mender-artifact

.travis.yml
README.md

Add travis configuration.

---

artifacts.go
metadata/metadata.go
writer/writer.go
writer/writer_test.go

Add some placeholder main function.

---

README.md
metadata/metadata.go
metadata/metadata_test.go
writer/file_archiver.go
writer/stream_archiver.go
writer/writer.go
writer/writer_test.go

Make golint happy.

---

metadata/metadata.go
writer/writer.go

Add comments to exported error variables. Fix go format warning.

---

writer/writer_test.go

Remove temp directories after tests.

---

parser/rootfs_parser.go

Return correct updates from GetUpdateFiles().

---

.travis.yml

Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>

Remove coveralls from build system

---

parser/rootfs_parser.go

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>

parser/rootfs_parser: fix typo in image type

---

README.md

@pasinskim can you pls review, especially the "using the library" part?

standardize README.md like for other repos

---

writer/writer.go

Do not crash when can not create artifacts file.

---

parser/generic_parser.go
parser/rootfs_parser.go
writer/writer.go

Some small fixes to artifacts library.

---

artifacts.go
reader/reader.go

Fix adding multiple devices form CLI.
Fix printing version and format using CLI.
Change error messages while reading artifact.

Artifacts library fixes.

---

reader/reader.go
reader/reader_test.go
test_utils/test_utils.go
writer/writer_test.go

Fix reading artifact containing multiple updates.

---

.travis.yml

@eysteins was trying to get this working locally.
I think its a good idea to just deploy this to s3 whenever tests are passing.
@pasinskim what do you think?

travis: upload binary to s3 bucket

---

.travis.yml

Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

fixup! travis: upload binary to s3 bucket

---

artifacts.go
artifacts_test.go
reader/reader.go

Rename artifacts to mender-artifact and simplify CLI.

---

README.md
archiver/metadata_archiver.go
artifacts.go
artifacts_test.go
parser/generic_parser.go
parser/parser_manager.go
parser/rootfs_parser.go
reader/reader.go
reader/reader_test.go
writer/writer.go
writer/writer_test.go

Some imports and tests need to be updated to work witch changed name.

Update dependencies after changing repository name.

---

.travis.yml
Makefile
artifacts.go
parser/rootfs_parser.go

This will add nice features such as an automatic version string in the
built binary, as well as build steps that are reusable outside of
Travis.

MEN-897: Import Makefile from mender client and respect Version.

---

parser/parser_manager.go

Add comments to the UpdateFile structure fields.

---

Makefile

Makefile: Make sure we don't ignore return codes inside for loop.

---

Documentation/artifact-format.md

Document new script API for artifacts.

---

artifacts.go
artifacts_test.go
awriter/writer.go

MEN-1014: Add ability to specify directory as state script source.

---

areader/reader.go
areader/reader_test.go
artifact/raw.go
artifacts.go
artifacts_test.go
awriter/writer.go

MEN-1220 Sign existing artifacts using mender-artifact CLI

---

artifact/raw.go

Update raw.go license information.

---

areader/reader.go
areader/reader_test.go
artifact/raw.go
artifacts.go
artifacts_test.go
awriter/writer.go

MEN-1220 Sign existing artifacts using mender-artifact CLI
(cherry picked from commit 67e9167c50099e47061feb586c7d0a4622ee7e3f)
Modified-by: Kristian Amlie <kristian.amlie@northern.tech>
- Tweaked imports to fix compile
- Added correct copyright on new file
Conflicts:
artifacts.go

2.0.x cherry-picks

---

artifacts.go

If /tmp directory is not the same partition as the directory
where modified artifact is stored, we are ending up with the following
error while modifying artifact: invalid cross-device link.
This is storing temporary artifact file in the same location where
the original one is placed.
Signed-off-by: Marcin Pasinski marcin.pasinski@northern.tech

Create temporary artifact in the directory where original one is

---

.travis.yml

Signed-off-by: Gregorio Di Stefano <greg.distefano@gmail.com>

travis-ci: only upload mender-artifact binary

---

.travis.yml

Changelog: none
Signed-off-by: Gregorio Di Stefano <greg.distefano@gmail.com>

fixup! travis-ci: only upload mender-artifact binary

---

artifact/signer.go

In some cases the size of ECDSA keys is different than expected
32 bits. In those cases we've been storing both r and s keys in one
serialized slice (first half was s and the other r). In case of shorter
key we've been storing the key starting from the beginning of the slice
leaving trailing parts of the slice zeroed. This was causing issues
while reading the key and deserializing the whole 32 bits of the stored
slice.
Now we are using offset to leave the leading zeros of the buffer. This
is having no impact on storing and reading the serialized keys.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
(cherry picked from commit 2119dcd2e3a2ad97eac2f6cf9354b966b15336bc)

MEN-1470 Fix ECDSA failures while signing and verifying artifact.

---

artifact/signer.go
vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh
vendor/vendor.json

Update mendertesting dependency and affected copyright years.

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go

Install function added 

---

.travis.yml
Makefile

Add mtools as a dependency before installing from source, and in travis

---

Documentation/artifact-format.md

Updated the JSON format of header-info version 3.

---

cli/mender-artifact/sign.go

FIX: MEN-2166: Renaming a file across devices now works.

---

README.md

Update the dead logo-link in the Readme.

---

Documentation/artifact-format-v3.md
LICENSE
LIC_FILES_CHKSUM.sha256
areader/reader.go
areader/reader_test.go
artifact/metadata.go
artifact/metadata_test.go
awriter/writer.go
awriter/writer_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/read.go
cli/mender-artifact/sign_test.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go
handlers/common.go
handlers/generic.go
handlers/generic_test.go
handlers/module_image.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

I recommend reviewing commit by commit, since they are quite unrelated.

Further Mender artifact v3 adjustments after client work

---

cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go

FIX: mender-artifact modify did not repack a sdimg after modification.

---

cli/mender-artifact/debugfs.go
cli/mender-artifact/main.go

Report a human readable error in case the artifact payload is not ext4.

---

Makefile

Apply coverage analysis to all subpkgs using -coverpkg flag

---

.travis.yml

Remove unit testing with go version 1.10

---

cli/mender-artifact/main.go

Update Author in help text to Northern.tech AS. 

---

areader/reader_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/partition.go

Contains also changes from PR #194.
For this PR, the commits under review are from 38ae1c5 onward.

MEN-2487: Not supported module-image operations

---

Dockerfile.binaries
Makefile

the squashed + rebased alternative to https://github.com/mendersoftware/mender-artifact/pull/190
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

added make task to build for multiple platforms

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go

MEN-2506: Throw a CLI error in case of a copy error. 

---

.travis.yml
Dockerfile.binaries
Makefile

Added a build step for macOS to the Travis build.

---

.travis.yml
tests-acceptance-mac/ma-read-output.golden
tests-acceptance-mac/ma-write-help-text.golden
tests-acceptance-mac/test-mac.sh

MEN-2505: Test the mac-binary on macOS in Travis. 

---

.gitignore
Dockerfile.binaries
Makefile

See individual commits for details.

Several multi-platform build fixes

---

awriter/signer.go
cli/mender-artifact/sign.go
cli/mender-artifact/sign_test.go

MEN-2573: Fix non-rootfs Artifacts being destroyed when signing them.

---

awriter/signer.go

Enable signing of artifacts larger than 1MiB

---

cli/mender-artifact/copy_test.go

Do not close the pipe in TestCopyFromStdin twice

---

cli/mender-artifact/partition.go

@lluiscampos This should solve your issues. Feel free to have a look. I have not added tests for it yet, but they will be here by the end of the day, in the meantime I don't see any issues trying merging this really, if it is still urgent for you

FIX: Buffer writes from stdin, and flush on close

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/modify_existing_test.go
utils/binpath.go
utils/binpath_test.go

Update formatting of files that were out of sync with gofmt

---

.gitlab-ci.yml
areader/reader_test.go
awriter/writer.go
awriter/writer_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/debugfs.go
cli/mender-artifact/debugfs_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/partition.go
cli/mender-artifact/partition_test.go
cli/mender-artifact/read.go
cli/mender-artifact/read_test.go
cli/mender-artifact/validate_test.go

This is best reviewed commit by commit to understand the context.
This solves both [MEN-1669](https://tracker.mender.io/browse/MEN-1669) and [MEN-2592](https://tracker.mender.io/browse/MEN-2592).

Refactor and implement modification of attributes

---

README.md

Signed-off-by: Michael Clelland <michael.clelland@mender.io>

Adjusted link to logo file in README

---

areader/reader.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/modify_existing_test.go

Fix: Update `rootfs_image_checksum` provide when repacking Artifact.

---

cli/mender-artifact/util/tty.go
cli/mender-artifact/util/tty_windows.go
cli/mender-artifact/write.go

MEN-3276: Bugfix (cli/snapshot): signal-loop on ignored signals - 3.3.x

---

Documentation/artifact-format-v3.md

Document the differences between [the JSON spec](https://stackoverflow.com/a/13502497/4471524) and JSON data handled by this software.

MEN-3414: describe JSON limitations

---

.github/stale.yml

Configures the stalebot for our use.

Added '.github/stale.yml' to configure the github stalebot

---

Documentation/artifact-format-v3.md

Clarify restrictions on JSON content in `meta-data` file in Artifacts.

---

cli/mender-artifact/util/tty.go
cli/mender-artifact/write.go

changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

MEN-3580: Fix creating artifact from snapshot terminating on SIGCHLD

---

cli/mender-artifact/util/tty.go
cli/mender-artifact/write.go

MEN-3580: Fix creating artifact from snapshot terminating on SIGCHLD - 3.3.x

---

areader/reader.go

This was inspired by:
https://hub.mender.io/t/directory/325/45

Add a message reminding the user to check for missing Update-Module

---

cli/mender-artifact/main.go

Just remember to sort them all

Recursively sort flags and commands to any depth

---

.gitlab-ci.yml
Makefile

Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

Update gitlab CI/CD pipeline to use golang:1.14-alpine3.11

---

.gitlab-ci.yml
Makefile
cli/mender-artifact/dump.go

[3.4.x] MEN-3967: Fix segfault on mender-artifact dump for v2 Artifacts

---

Documentation/artifact-format-v3.md
areader/reader.go
areader/reader_test.go
artifact/checksum.go
artifact/compressor_gzip_test.go
artifact/metadata.go
artifact/signer.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/dump.go
cli/mender-artifact/dump_test.go
cli/mender-artifact/future_flags_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/read.go
cli/mender-artifact/read_test.go
cli/mender-artifact/template.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go
handlers/common.go
handlers/module_image.go
handlers/rootfs_image.go

Which also means adding `clears_artifact_provides` field to the Artifact format. See individial commits for details.

MEN-3479: Add `--clears-provides` flag.

---

cli/mender-artifact/main.go
cli/mender-artifact/template.go

go fmt alignment

---

Makefile

Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

Fix: gocyclo refactoring and switch to go mod

---

Makefile
cli/mender-artifact/write.go

ChangeLog:title
(cherry picked from commit 63eea38f8eca8855864695df144f3a01a7d1ad8d)

MEN-3987 use sudo for snapshots if required.

---

.gitlab-ci.yml
Makefile
artifact/checksum.go
artifact/compressor_gzip_test.go
artifact/signer.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/debugfs_test.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/partition.go
cli/mender-artifact/platform_test.go
utils/binpath.go
utils/binpath_test.go

Best reviewed commit by commit, most changes are small and self contained.

QA-212: Enable unit testing and coverage reporting from Mac OS.

---

LICENSE
LIC_FILES_CHKSUM.sha256
Makefile
artifact/stage/stage.go
cli/mender-artifact/dump_test.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/write_test.go
go.mod
go.sum
utils/attributes.go
utils/attributes_test.go
vendor/github.com/urfave/cli/app.go
vendor/github.com/urfave/cli/command.go
vendor/github.com/urfave/cli/context.go
vendor/github.com/urfave/cli/flag_int64_slice.go
vendor/github.com/urfave/cli/flag_int_slice.go
vendor/github.com/urfave/cli/flag_string_slice.go
vendor/modules.txt

* go fmt artifact, cli and utils packages
* [LICENSE] Update copyright year to 2021
* [Makefile] Fix gofmt test in extracheck target
It as missing a semi-colon, so on error it would echo "/bin/false".
Aligned a with the Makefile from mender-connect
* #314 
* [write_test] Adjust expected output after urfave/cli upgrade

Misc: go fmt + copyright + Makefile fix + dependabot + test fix

---

LICENSE
LIC_FILES_CHKSUM.sha256

(cherry picked from commit b2a6299554a330611b39ac8707e43cd06f98bba2)

[LICENSE] Update copyright year to 2021

---

cli/mender-artifact/write.go

This can potentially fix a broken Artifact, and is harmless otherwise.

MEN-4362: run fsck on fs image created via SSH snapshot

---

cli/mender-artifact/write.go

3.4.x: MEN-4362: run fsck on fs image created via SSH snapshot

---

.gitlab-ci.yml

3.5.x: [pipeline] Add trigger:mender-qa job

---

awriter/writer.go

Add missing error description when artifact header can't be written.

---

cli/copy.go
cli/copy_test.go
cli/partition.go

3.6.x: MEN-5076: cli: Fix parsing of filenames containing ".mender"

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/partition.go

3.5.x: MEN-5076: cli: Fix parsing of filenames containing ".mender"

---

.gitlab-ci.yml
cli/partition.go
cli/write.go

3.6.x: MEN-5082: Restore SSH snapshot feature on Mac OS

---

.gitlab-ci.yml
areader/reader.go
artifact/compressor_gzip.go
artifact/compressor_lzma.go
artifact/compressor_none.go
artifact/metadata.go
artifact/scripter.go
awriter/signer.go
awriter/writer.go
cli/artifacts.go
cli/cli.go
cli/copy.go
cli/debugfs.go
cli/dump.go
cli/modify.go
cli/partition.go
cli/read.go
cli/sign.go
cli/template.go
cli/util/tty.go
cli/validate.go
cli/write.go
handlers/common.go
handlers/module_image.go
handlers/rootfs_image.go
utils/attributes.go
utils/binpath.go
utils/progress.go

QA-235: pipeline: Switch to static checks by golangci-lint

---

.gitlab-ci.yml
tests-acceptance-mac/test-mac.sh

chore: add the missing shell license headers

---

Documentation/artifact-format-v3.md
areader/reader.go
areader/reader_test.go
artifact/metadata.go
artifact/metadata_test.go
awriter/writer.go
cli/artifacts.go
cli/artifacts_test.go
cli/cli.go
cli/cli_test.go
cli/dump.go
cli/read.go
cli/read_test.go
cli/write.go
cli/write_test.go
handlers/bootstrap_artifact.go
handlers/bootstrap_artifact_test.go
handlers/common.go
handlers/common_test.go
handlers/module_image.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

feat(zero-payload): Implement read and write for zero payload artifacts
Ticket: MEN-2586
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

feat(zero-payload): Implement read and write for zero payload artifacts

---

.gitlab-ci.yml
tests/test_sign_with_hsm/config.sh
tests/test_sign_with_hsm/functions.sh
tests/test_sign_with_hsm/setup.sh
tests/test_sign_with_hsm/test_sign_with_hsm.sh

Sign with HSM test.

---

tests/test_sign_with_hsm/config.sh
tests/test_sign_with_hsm/functions.sh

Ticket: MEN-5933
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

test: verify artifacts signed with PKCS#11 using file-based public key

---

.gitlab-ci.yml
Makefile
cli/read.go

Ticket: MEN-5833
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

chore(CI/CD): collect code coverage from PKCS#11 test

---

apk-run-requirements.txt

Ticket: MEN-5906
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

chore: apk requirements to run mender-artifact on alpine

---

artifact/compressor_gzip.go

pref: Use best gzip compression by default

---

README.md
tests-acceptance-mac/test-mac.sh

chore: update bug tracker link

---

.gitlab-ci.yml
LICENSE
LIC_FILES_CHKSUM.sha256
cli/read.go

ci: Update jobs tags for new runners

---

artifact/compressor_lzma_test.go
artifact/compressor_zstd_test.go
artifact/signer.go
cli/cli.go
cli/partition.go
cli/template.go
cli/util/tty_bsd.go
cli/util/tty_windows.go

fix: load keys with ParsePKCS8PrivateKey.
Ticket: None

Load keys with ParsePKCS8PrivateKey

---

README.md

fix: add compilation instructions to README

---

areader/reader.go

fix zstd compression support

---

.gitlab-ci.yml
tests/test_compressions/test_supported_compressions.sh

test: smoke tests for supported compression types.

---

Documentation/artifact-format-v3.md

Ticket: None
Signed-off-by: Craig Comstock <craig.comstock@northern.tech>

fix: typo in artifact format docs

---

.gitlab-ci.yml

Add arm64 docker build

---

cli/copy.go
cli/copy_test.go

https://northerntech.atlassian.net/browse/MEN-5463

MEN-5463 use source file name if destination file name is not supplied

---

cli/copy_owner.go
cli/copy_owner_windows.go
cli/sign.go
cli/sign_test.go

fix: signing an existing artifact now preserves file permissions

---

LICENSE
LIC_FILES_CHKSUM.sha256

chore: Bump copyright license year to 2025

---

artifact/keyfactor/signer.go
cli/debugfs.go
cli/sign.go
cli/sign_test.go
cli/write.go

fix: fixed signing artifact via symlink

---

cli/write.go

fix: Include all provides with prefix rootfs when writing artifact via SSH

---

LIC_FILES_CHKSUM.sha256
cli/cli.go
cli/write.go
go.mod
go.sum
vendor/github.com/mendersoftware/progressbar/LICENSE
vendor/github.com/mendersoftware/progressbar/LIC_FILES_CHKSUM.sha256
vendor/github.com/mendersoftware/progressbar/README.md
vendor/github.com/mendersoftware/progressbar/progress.go
vendor/modules.txt

Changelog: Add progress bar to command `write module-image`

MEN-8127: Fix output for `write module-image`

---

artifact/scripter.go

The static tests complains:
`should omit nil check; len() for nil slices is defined as zero (gosimple)`
https://gitlab.com/Northern.tech/Mender/mender-artifact/-/jobs/9442633456

chore: omit nil check

---

.gitlab-ci.yml

ci: add docker retry

---

utils/binpath.go

It will now print e.g.:
`fsck command not found: Operations that use "fsck.ext4" are unfortunately not avaiable on Mac OS...`
Ticket: MEN-8324

chore: add verbose error message for fsck on Mac OS

---

Documentation/artifact-format-v3.md

docs: Make current support for only one payload in artifact v3 explicit in the documentation
