writer/file_archiver.go
writer/stream_archiver.go

Both FileArchiver and StreamArchiver are using annonymous
struct members to implement part of ReadArchiver interface.

Simplify archive writing by using anonymous structs.

---

parser/rootfs_parser.go
reader/reader_test.go

New rootfs parser method - GetImageID.
Method similar to GetDeviceType.
Required metadata fields are DeviceType and ImageID.
There is GetDeviceType() method already, but there was no GetImageID() method.
Signed-off-by: Krzysztof Jaskiewicz <krzysztof.jaskiewicz@open-rnd.pl>

Parser: GetImageID method

---

parser/generic_parser.go
parser/rootfs_parser.go
reader/reader.go
reader/reader_test.go
writer/writer_test.go

The user of `RootfsParser` can provide `DataFunc` to receive a decompressed update data stream along with information about device type and current update.
Additional minor enhacements that remove the need for specialized `New..Parser`.
Do not merge yet, still missing tests.
@pasinskim @kacf

Support for passing incoming update data stream to the caller

---

artifacts.go
parser/generic_parser.go
parser/parser_manager.go
reader/reader.go

So far we've been returning the parser type as a update-type for a given update. This was correct for the specific update type parsing (like `rootfs-image`), as to use a given parser we need to have a match between parser parsing type and update type itself.
For the generic parser though, we've been returning `generic` as a given update type even though the exact type was different.
There are also some fixes and improvements added:
- missing space in error messages while using CLI tool
- always using `GenericParser` as a default parser type

Use the exact update type as a type-info parameter.

---

reader/reader.go

After tar reader returns error, `hdr` variable might be left unset
in `ReadNextDataFile` and dereferencing it to log the `hdr.Name`
ends up with panic.

MEN-952 Fix reader panic while reading malformed tar archive.

---

artifacts.go

While using `mender-artifact` CLI it crashed without providing
device type.

MEN-1028 don't crash when device type in not provided.

---

artifact/signer_test.go

Changing the first byte of the signature is causing errors
while executing tests, when we are ending up with
"illegal base64 data at input byte 0".

Fix signer unit tests.

---

artifacts.go
artifacts_test.go

Also remove the section that auto-promotes version to 2 under certain
conditions. This code will never execute anymore now that the default
is 2.

MEN-1183: Switch default artifact format version to 2.

---

areader/reader.go
areader/reader_test.go

If we are expecting artifact to be signed, `NewReaderSigned`
instead of `NewReader` should be used. This will allow failing
immediately after discovering that signature is missing.

MEN-1198 Stop reading artifact when signature is missing.

---

areader/reader_test.go
artifact/scripter.go
artifact/scripter_test.go
artifacts_test.go
awriter/writer_test.go

Use `STATE_[Enter|Leave|Error]_NUM[_optional-script-name]` schema
for naming state scripts.

Update state scripts to new naming schema.

---

artifacts.go
artifacts_test.go

For version 2.0 we are disabling the ability of adding state
scripts as the functionality is not implemented client and backend
side.
Changelog: Remove support for adding state script for version 2.0

MEN-1229 Remove parameter allowing adding scripts.

---

areader/reader_test.go
artifact/scripter.go
artifact/scripter_test.go
artifacts_test.go
awriter/writer_test.go

Instead of being part of the artifact Download state script
will be together with Idle and Sync scripts part of rootfs.

Make ArtifactDownload state part of rootfs script.

---

LIC_FILES_CHKSUM.sha256

Many licenses were incorrectly listed under Apache-2.0 license.

Clean up license checksums.

---

artifacts.go
artifacts_test.go

MEN-1355: mender-artifact now fails with whitespace in the artifact-name

---

artifacts.go

MEN-1328: Mender-Artifact now returns an error code to the os on cli errors
(cherry picked from commit 45623fc58717c15c32068c7e33aa57b85f1dbf2e)

2.0.x cherry-picks

---

artifacts.go

MEN-1328: Mender-Artifact now returns an error code to the os on cli errors
(cherry picked from commit 45623fc58717c15c32068c7e33aa57b85f1dbf2e)

2.1.x cherry-picks

---

areader/reader.go
artifact/checksum.go

For reading and verifying header checksum we are using checksum.Reader.
Internal inplementation of checksum.Reader is using io.TeeReader for
calculating checksum and reading the stream at the same time.
After receiving EOF checksum should be checked automatically inside
checksum.Reader, but if we are inside tar archive error is not passed up
the stack to tar.Reader.
The workaround is to check the sum again after the whole header is read.

MEN-1412 Fix broken header checksum verification.

---

artifact/signer.go
artifacts.go
modify_existing_test.go

Now it is possible to modify signed artifact. The public key is
extracted form provided private key and the artifact is validated
before it can be signed.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

MEN-1213 Fix modifying signed artifact.

---

artifact/signer.go

In some cases the size of ECDSA keys is different than expected
32 bits. In those cases we've been storing both r and s keys in one
serialized slice (first half was s and the other r). In case of shorter
key we've been storing the key starting from the beginning of the slice
leaving trailing parts of the slice zeroed. This was causing issues
while reading the key and deserializing the whole 32 bits of the stored
slice.
Now we are using offset to leave the leading zeros of the buffer. This
is having no impact on storing and reading the serialized keys.
Changelog: Tile
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

MEN-1740 Fix ECDSA failures while signing and verifying artifact. 

---

Documentation/artifact-format.md

Add a new documentation for version 3 of Mender artifact.
This contains `artifact_provides` and `artifact_depends` sections
needed for updates ordering as well as some preliminary additions
for delta updates.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

MEN-1667 Artifact version 3 format documentation

---

LICENSE
LIC_FILES_CHKSUM.sha256

Makes it easier to have a common license checking facility in the
license-overview-generator script.
Changelog: Small cleanup of license text. No legal difference, just
makes it easier for the tooling.

Unify LICENSE file so it matches other repositories.

---

.gitignore

Microsoft Visual Studio Code creates a .vscode directory
to hold user settings and other things that don't belong
in source control.  Updated .gitignore to ignore this directory.
Signed-off-by: Don Cross <cosinekitty@gmail.com>

Tell git to ignore Visual Studio Code directory ".vscode"

---

cli/mender-artifact/validate.go
cli/mender-artifact/validate_test.go

Changelog: A command of the form
"mender-artifact validate unsigned.mender -k public.key"
was incorrectly succeeding for an unsigned artifact when a public key
was supplied. Supplying a public key indicates that the caller requires
the artifact to contain a signature that matches that key.
Now this command fails (exits with a nonzero value) as expected.
Fixed logic in validate function to return an error when
a public key was given but we never received a callback to
validate a signature inside the artifact.
Also fixed a problem where some callers (for example,
the new "cat" command) call validate with "" instead
of nil to indicate a missing key.
Added 2 more unit tests:
- Must fail validation of an unsigned artifact with key given.
Confirmed this test failed before the fix mentioned …

MEN-2155 Fail validate when key supplied for unsigned artifact

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/validate.go
cli/mender-artifact/validate_test.go

Changelog: Fixed a bug that caused a command like
"mender-artifact cat signed.mender:/etc/mender/artifact_info"
to fail with the error:
"failed to open the partition reader: err: error validating signature"
There was a similar problem with the "cp" command, and also
the "modify" command when no "-k" was present to replace the
existing signature.
This change is based on the general idea that if the user
does not specify a public key, he is saying he does not want
to authenticate a digital signature, whether or not one exists
in the artifact.
Simplified the validate function so it no longer returns an
error if the artifact contains a signature but no public
key was specified by the caller.
Added a unit test that used to fail before the bug was fixed,
and now it passes.
Updated existing unit …

MEN-2169 Fix mender-artifact "cat", "cp", "modify" on signed artifacts.

---

.travis.yml
cli/mender-artifact/artifacts.go

Previously an update present in a directory, with the same name as the
update present in an update would be removed as a result of what the
functions thought was tmp-files.
MEN-2171
(cherry picked from commit 78544a96c18a5e81cb7bc141c918e08646c70ced)

[2.3.x] FIX: mender-artifact cat,cp,modify etc no longer removes the update.

---

Makefile

This should be considered a temporary measure, and a better method
should be considered later, such as not including simple "check error
and return" branches in the gocyclo count, since this is needed
*everywhere* in Go code.

Increase gycyclo limit to allow error checking in simple functions.

---

areader/reader.go
areader/reader_test.go
artifact/compressor.go
artifact/compressor_gzip.go
artifact/compressor_gzip_test.go
artifact/compressor_none.go
artifact/compressor_none_test.go
artifact/compressor_test.go
artifact/update.go
awriter/writer.go
awriter/writer_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/partition.go
cli/mender-artifact/sign.go
cli/mender-artifact/write.go
handlers/common.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

Just a preview to allow further discussions.
Currently the gocyclo test fails, so we probably have to refactor these functions:
```
16 main signExisting ./cli/mender-artifact/sign.go:27:1
16 main modifyArtifact ./cli/mender-artifact/modify.go:31:1
```

[WIP] MEN-2224 Support uncompressed updates

---

cli/mender-artifact/debugfs.go
cli/mender-artifact/debugfs_test.go

FIX: executeCommand failed to return an error if a command failed.

---

cli/mender-artifact/debugfs.go
cli/mender-artifact/debugfs_test.go

(cherry picked from commit c5b409f97448e1ba6380dbd2a8bb1f5c31ca4242)

[2.3.x] FIX: executeCommand failed to return an error if a command failed.

---

cli/mender-artifact/copy.go

FIX: mender-artifact cat now cleans up resources on write-errors.

---

.travis.yml
LIC_FILES_CHKSUM.sha256
areader/reader_test.go
artifact/compressor.go
artifact/compressor_gzip_test.go
artifact/compressor_lzma.go
artifact/compressor_lzma_test.go
artifact/compressor_none.go
artifact/compressor_none_test.go
artifact/compressor_test.go
awriter/writer.go
cli/mender-artifact/main.go
handlers/rootfs_image.go
vendor/github.com/mendersoftware/go-liblzma/LICENSE
vendor/github.com/mendersoftware/go-liblzma/enums.go
vendor/github.com/mendersoftware/go-liblzma/reader.go
vendor/github.com/mendersoftware/go-liblzma/writer.go
vendor/vendor.json

This depends on PR #150, which I have merged into this PR for the time being. Other than that I think it should be good to go. I don't have any hardware to hand so I can't test a real deployment, but the CLI tool can read the artifact back so I can't see any reason why it wouldn't work.

Add support for compressing artifacts using LZMA

---

artifact/compressor_lzma.go

As the lzma compressor is dependent upon go-liblzma, which has a cgo dependency,
this will not build when cgo is disabled.

MEN-761: Added a cgo tag to the lzma compressor.

---

artifact/tar_writer_stream.go
handlers/common.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

Updated code-coverage in rootfs_image.go

---

.travis.yml

We use Jenkins to deploy mender-artifact.

travis: Get rid of broken and unused deploy step.

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/debugfs.go
cli/mender-artifact/partition.go
utils/binpath.go
utils/binpath_test.go

Certain commands are spawned from the mender-artifact command and those
commands may sometimes live outside of $PATH (since /sbin, /usr/sbin,
.. is normally not in a regular users path). First search PATH but
also try other locations.
Adresses: https://tracker.mender.io/browse/MEN-2180
Changelog: fixes issue when binary dependencies are not in PATH
Signed-off-by: Andreas Henriksson <andreas@fatal.se>

Use GetBinaryPath helper to search PATH and sbin

---

cli/mender-artifact/debugfs.go

@kacf please take a look. tested:
`#./mender-artifact modify /tmp/qemux86-64-uefi-grub_release_1_master.mender --server-uri "$MENDER_SERVER_URL" --tenant-token "$MENDER_TENANT_TOKEN"
Error modifying artifact[/var/folders/c_/j5f_xrnj3790c0pbm3bg_rwm0000gn/T/core-image-full-cmdline-qemux86-64.ext4]: fsck.ext4 command not found.
`

checking if fsck is on path and returning error if not.

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/debugfs.go
cli/mender-artifact/debugfs_test.go
cli/mender-artifact/partition.go
utils/binpath.go
utils/binpath_test.go

Changelog: The mender-artifact tool now checks whether the required
external binaries can be found on the system, and if not, returns an appropriate
error message.

MEN-2180: Document mender-artifact dependency upon `debugfs` 

---

.dockerignore
Dockerfile
Makefile

While moving other parts of mender to contained docker builds, mender-artifact would also be a nice to have. Due to the lzma dependency this is not based on scratch or busybox, but alpine.
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

Added multi stage dockerfile to contain builds

---

cli/mender-artifact/debugfs.go

Same as for the rest of binaries expected to be in /sbin or /usr/sbin.
It seems like this one was missed in commit 91d0f27 (PR #184)

Look for fsck.ext4 via GetBinaryPath

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/modify_existing_test.go

It was not working for Artifact V3 headers. Extended the unit tests to
cover both supported versions.

MEN-2488: Fix name modify command for rootfs-image Artifacts

---

cli/mender-artifact/artifacts.go
cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/partition.go
cli/mender-artifact/sign.go

MEN-2486: Remove support for re-signing modified artifacts
It was not properly implemented; the "-k" parameter was being used as
the public key to verify the signature of the current Artifact and as
the private key as well to sign the modifyied Artifact.
In any case, it is better to completely remove this option and use the
mender-convert sign after modifications to produce the final Artifact
Removed the functionality and improved the test to actually check
something after the modifications.
Changelog: `mender-artifact modify` does not support anymore signing the
Artifact after the modification. Use `mender-convert sign` after the
modification to sign the Artifact.

MEN-2486: Unsupport signed modify

---

areader/reader.go
cli/mender-artifact/dump.go
cli/mender-artifact/dump_test.go
cli/mender-artifact/main.go
handlers/rootfs_image.go

It takes an artifact as input, some optional dumping directories, and
writes the various raw files from the artifact into those directories.
The parameter `--print-cmdline` can be used to generate a command line
which can be used to recreate the same artifact from the dumped files.

MEN-2580: Add `dump` command to mender-artifact.

---

areader/reader.go

We need to use `errors.Cause()` to handle wrapped EOF errors
correctly, which may be returned by advanced Readers (network streams,
etc.).
Changelog: title

Fix spurious upload errors due to wrong EOF handling.

---

cli/mender-artifact/dump.go
cli/mender-artifact/dump_test.go

Fix missing `--provides` and `--depends` options in dumped cmdline.

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go

MEN-2745: 'mender-artifact cp' now requires '-' in order to read stdin

---

cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go

Fix: mender-artifact modify did not clean up the temp-files created

---

cli/mender-artifact/copy_test.go

Port bugfix to 3.1.x
This should have been ported between beta and final 3.1.0... But anyway, let's get it in now so that can be part of 3.1.1

Do not close the pipe in TestCopyFromStdin twice

---

Dockerfile

The Dockerfile for creating mender-artifact image was serving the binary
directly from go/src/..., so the build-contained target was not able to
extract it from the expected go/bin/ directory.

Fix build-contained Makefile: image was missing make install

---

.dockerignore

```
Remove .dockerignore so that the full repo is copied to the image
As the Dockerfile itself was not being sent to the Docker image, git in
the running container will detect it as a deleted file, triggering then
a "-dirty" suffix in the version string.
Changelog: MEN-2800: fix erroneously report of "-dirty" in the version
string.
```

MEN-2800: fix erroneously report of "-dirty" in the version string.

---

.dockerignore

Remove .dockerignore so that the full repo is copied to the image
As the Dockerfile itself was not being sent to the Docker image, git in
the running container will detect it as a deleted file, triggering then
a "-dirty" suffix in the version string.
Changelog: MEN-2800: fix erroneously report of "-dirty" in the version
string.
(cherry picked from commit 4c28f23dc8f7532aa58597674d5ed9415fede897)

MEN-2800: fix dirty version string - Port to 3.1.x

---

cli/mender-artifact/main.go
cli/mender-artifact/main_test.go

This allows it to be appended to the command, which makes it usable
with `--` style arguments to Update Module Artifact generators.

Allow `--compression` to be specified after command.

---

Documentation/artifact-format-v3.md

This commit updates the description of the values allowed in the type-info
headers in the version 3 of the artifact format. Formerly only the key
`rootfs-image-checksum` was allowed, while now, any key is allowed, with
the only allowed value types being string, or array of strings.

Update the type-info documentation in the version 3 artifact format

---

artifact/metadata.go
artifact/metadata_test.go
cli/mender-artifact/read.go
cli/mender-artifact/write.go

Previously the artifact-depends key in the type-info header was restricted
to contain a single key `rootfs-image-checksum`. This restriction has now
been lifted, and the key can now contain arbitrary string, and []string values.

Enable typeinfo artifact-depends/provides string and []string values

---

cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go

MEN-2758
(cherry picked from commit 7c5ec50a8b72e81cea79eaf7cc190696012bf6fc)

[3.1.x] Fix: mender-artifact modify did not clean up the temp-files created

---

areader/reader.go
areader/reader_test.go
artifact/metadata.go
artifact/metadata_test.go
awriter/writer.go
awriter/writer_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/read_test.go
cli/mender-artifact/sign_test.go
cli/mender-artifact/validate_test.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go
handlers/common.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

Changelog: Mender-Artifact format version 1 is hereby deprecated,
and neither reading or writing the version 1 of the format is no longer
supported. Please move to using a newer version.

MEN-2156: Remove support for Mender-Artifact format version 1

---

cli/mender-artifact/validate.go
cli/mender-artifact/validate_test.go

Changelog: mender-artifact will now fail to validate a signed artifact
if no validation key is specified. No behaviour change for unsigned
artifacts.

MEN-2802: Do not validate signed Artiafcts without a key

---

cli/mender-artifact/main.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go

Previously, the `write rootfs-image` command did not have the ability
to set Provides and Depends in the artifact. This was only enabled for
the `write module-image` command. Now the `rootfs-image` update can
also set Provides and Depends. However, please note that meta-data
and augmented Provides and Depends still are unsupported.
Changelog: commit

MEN-2812: Enables Artifact Provides and Depends for write rootfs-img

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go

The bug was related to wrong file permissions on the files which were copied over to the target using debugfs. In fact, these were always 0600, as the temp-files did not even have the permissions changed. 
This PR changes that fact, although this implementation did also stumble into some issues (umask overriding the permissions set on creation of the temp-file.

MEN-2880: Make artifact install respect the given file permissions

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go

The current Mender-Artifact install functionality had a bug in which the
temp-files it creates and uses for moving a file from the host to the target
with debugfs were created with the standard file permissions (0600). This did
pass test as only (0600) was tested. This fix creates a new temp-file, and
explicitly sets the file-permissions on it to match the one given on the command
line.
It has also added a couple of more test cases (0777, 0700) to make sure that the
same error as seen before does not slip unnoticed through the tests.

[Cherry] MEN-2880: Make artifact install respect the given file permissions

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go

The current Mender-Artifact install functionality had a bug in which the
temp-files it creates and uses for moving a file from the host to the target
with debugfs were created with the standard file permissions (0600). This did
pass test as only (0600) was tested. This fix creates a new temp-file, and
explicitly sets the file-permissions on it to match the one given on the command
line.
It has also added a couple of more test cases (0777, 0700) to make sure that the
same error as seen before does not slip unnoticed through the tests.

[Cherry] MEN-2880: Make artifact install respect the given file permissions 

---

areader/reader_test.go
artifact/metadata.go
artifact/metadata_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/dump.go
cli/mender-artifact/modify.go
cli/mender-artifact/read.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go
handlers/common.go
handlers/module_image.go
handlers/module_image_test.go
handlers/rootfs_image.go
handlers/rootfs_image_test.go

Previously artifact.TypeInfoDepends was of type pointer to map.
This commit removes the pointer, as every map in go is imiplicitly a pointer to
a map, and hence the extra pointer is unnecessary, and in fact has caused a lot
of fugly code in order to mitigate this poor design choice.

Change the type of artifact.TypeInfoDepends and Provides 

---

cli/mender-artifact/main.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/read_test.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go

Previously the `write rootfs-image` command did not write the provided checksum
to the Artifact.
This commits makes sure the checksum is always provided when writing a
rootfs-image Artifact.

MEN-2956: Write `rootfs_image_checksum` provides in rootfs-image

---

cli/mender-artifact/copy.go

Previously we were allowing only Yocto naming convention sdimg, uefiimg,
but it might come in handy to modify a .img image (i.e. converted
Raspbian).

Accept suffix '.img' for mender-artifact modifiable images

---

areader/reader.go
areader/reader_test.go
artifact/metadata.go
artifact/metadata_test.go
utils/json.go
utils/json_test.go

In the current state, the MergeArtifactDepends/Provides forces a value to unset struct values which conflicts with the json tags which has side-effects when attempting to match dependencies with provides.

FIX: MergeArtifact[Depends|Provides] obeys json tags

---

.gitlab-ci.yml

Cherry picking c48a4ca into 3.3.x

[pipeline] Set docker:dind image to a fixed version - 3.3.x

---

cli/mender-artifact/util/tty.go
cli/mender-artifact/util/tty_windows.go
cli/mender-artifact/write.go

If the forked ssh process received a signal which is ignored by default,
the signal is re-invoked using unix.Kill. This inevitably lead to an
invalid syscall instruction in case of SIGCHLD.
This commit makes SIGCHLD trigger terminal echo to be restored and
exits with an error. SIGURG and SIGWINCH are the only ignored signals.

Bugfix (cli/snapshot): signal-loop on ignored signals

---

cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/debugfs.go
cli/mender-artifact/main.go
cli/mender-artifact/partition.go

This PR adds the ability to create directories (and nested directories) to the `mender-artifact install` command, mimicking the `install` utility syntax:
`mender-artifact install -d <artifact>:/dirs/to/create`
Signed-off-by: Sam Baxter <sbaxter@izotope.com>

Add ability for artifact install to create directories

---

README.md
autocomplete/bash_autocomplete
autocomplete/zsh_autocomplete
cli/mender-artifact/main.go

This PR
* Enables the auto-completion features from the mentioned library
* Documents how to enable it in the Readme
Then writing:
mender-artifact <TAB>
results in:
```
➜ mender-artifact git:(bashexpansion) ✗ mender-artifact
cat          -- cat [artifact|sdimg|uefiimg]:<filepath>
cp           -- cp <src> <dst>
dump         -- Dump contents from Artifacts
help      h  -- Shows a list of commands or help for one command
install      -- install -m <permissions> <hostfile> [artifact|sdimg|uefiimg]
modify       -- Modifies image or artifact file.
read         -- Reads artifact file.
rm           -- rm [artifact|sdimg|uefiimg]:<filepath>
sign         -- Signs existing artifact file.
validate     -- Validates artifact file.
write        -- Writes artifact file.
```
and
```
➜ mender-artifact …
```

Enabled shell auto-completion functionality

---

cli/mender-artifact/main.go
cli/mender-artifact/main_test.go

```
commit 0e8d4f7d2b35024340f8aabc647b0f6734b972cd
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Tue Jun 2 08:42:38 2020
Restore `module-image -f` flag as optional.
This was mistakenly made a required flag in da8a2d29da2fd.
commit b1ff041eed51fe0ccfd19614f0c0108a95225680
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Tue Jun 2 08:41:49 2020
test: Add missing error checking after command line parsing.
```

Restore `module-image -f` flag as optional.

---

Makefile
README.md
autocomplete/zsh_autocomplete

Simply add a Makefile target for installing the autocompletion scripts.

Add(Makefile): Target for installing the autocompletion scripts

---

cli/mender-artifact/dump.go

Check the Artifact v3 specific fields before accessing them, this fixes
a segfault when running `mender-artifact dump --print-cmdline` on a v2
Artifact.

MEN-3967: Fix segfault on mender-artifact dump for v2 Artifacts

---

.gitlab-ci.yml

this should just ensure the very basic functionality of the to-be-published binary
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

added very simple execution tests for mac (& linux) 

---

.gitlab-ci.yml
Documentation/artifact-format-v3.md
Makefile
artifact/metadata_test.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/artifacts_test.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/dump_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/read_test.go
cli/mender-artifact/write.go
cli/mender-artifact/write_test.go

This PR also includes MEN-3482: Change rootfs_image_checksum over to use namespaced provides.
Depends on:
* https://github.com/mendersoftware/integration/pull/1016
* https://github.com/mendersoftware/meta-mender/pull/1093
* https://github.com/mendersoftware/meta-mender/pull/1096

MEN-3076,MEN-3077: set software version in {rootfs,module}-image

---

.gitlab-ci.yml

Trivial build step - only runs make inside the repository.
Already tested this here: https://gitlab.com/Northern.tech/Mender/mender-artifact/-/pipelines/194156353

Add build:mac stage to the CI pipeline

---

utils/attributes.go
utils/attributes_test.go

This is implemented in mender-artifact so that the deployments backend
can use the same function as the client to calculate the effect on
provides values for a multi-stage upgrade path, should we ever
implement that.

MEN-3075: Implement function for filtering provides with clears_provides.

---

cli/mender-artifact/dump.go
cli/mender-artifact/dump_test.go
cli/mender-artifact/main.go

Works exactly like `--print-cmdline` but prints null bytes between
arguments instead of spaces. This mirrors the `-print0` argument of
find and complements the `-0` argument of xargs.

MEN-3483: Add `--print0-cmdline` argument to `dump` command.

---

cli/mender-artifact/write.go

Changes to sudo usage for snapshots; use sudo only if:
* sudo is present and works
* user is not root
ChangeLog:title

MEN-3987 use sudo for snapshots if present.

---

areader/reader.go
cli/mender-artifact/artifacts.go
cli/mender-artifact/copy.go
cli/mender-artifact/copy_test.go
cli/mender-artifact/main.go
cli/mender-artifact/modify.go
cli/mender-artifact/modify_existing_test.go
cli/mender-artifact/partition.go

Fixes the issue where modifying an artifact by any of the utility commands would change the compression to `gzip`, as the Artifact was always repacked with the standard compression. This would also destroy signed Artifacts using commands such as `cat` which should have no effect on the signature.
This led to the discovery along the way, that most commands did indeed not respect the `compression` flag - which claimed to be global in scope. Therefore, this removes the global claim from the helptext, and instead adds a note about the `compression` flag's functionality, which after all, if you read the note, was limited to only a few commands in scope.
I guess most people never used the `compression` flag with most of the utility commands (as it would not have worked). Therefore I feel these …

MEN-4502: Do not change the underlying Artifact unnecessarily

---

cli/mender-artifact/copy_test.go

This function is also used in most test case to clean-up temp files, so
remove the early return on test cases expecting error, so that we call
such function for all.
Introduced at a4bf948c.

[copy_test] Amend tests to always call verifyTestFunc

---

artifact/scripter.go
artifact/scripter_test.go
cli/mender-artifact/main.go
cli/mender-artifact/write_test.go

Notably:
* Improve the error message when adding a state script with a wrong naming scheme
* Add a missing article in the description of the output-path CLI description

Misc minor user facing nit-picks

---

cli/util/tty.go
cli/util/tty_windows.go
cli/write.go

There is a [potential race condition](https://golang.org/src/os/signal/signal.go#L199)
where signals sent right before or while signal.Stop is closed does not
reach the signal channel until after the function returns. In such cases
it can happen that the signal channel is closed before the signal has
been propagated to the handler. This commit instead of closing the
signal channel, uses a separate channel (context.WithCancel) to stop
listening for signals after calling signal.Stop.
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

[MEN-4832] Fix sending on closed signal channel

---

cli/mender-artifact/util/tty.go
cli/mender-artifact/util/tty_windows.go
cli/mender-artifact/write.go

There is a [potential race condition](https://golang.org/src/os/signal/signal.go#L199)
where signals sent right before or while signal.Stop is closed does not
reach the signal channel until after the function returns. In such cases
it can happen that the signal channel is closed before the signal has
been propagated to the handler. This commit instead of closing the
signal channel, uses a separate channel (context.WithCancel) to stop
listening for signals after calling signal.Stop.
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 64a6fc49023649a5bd9df020ec97076844f33976)

3.5.x: [MEN-4832] Fix sending on closed signal channel

---

areader/reader.go

This ensures that the checksum calculated is correct.

MEN-5094: Empty the tar reader to ensure a full read

---

areader/reader.go

3.6.x: MEN-5094: Empty the header reader before calculating the checksum

---

areader/reader.go

Changelog: Fix the checksum errors encountered in rare cases where the entire byte
stream is not consumed during verification, and thus giving wrong checksum errors.
(cherry picked from commit 8d0fb66d5371936490923bed4a25e2d3fce30beb)

[Cherry 3.5.x] MEN-5094: Empty the header reader before calculating the checksum

---

.gitlab-ci.yml
cli/partition.go
cli/write.go

While fixing MEN-4362, we introduced a dependency for the SSH snapshot
feature on `blkid`, in effect introducing a regression on Mac OS where
this tool is not present.
This commit amends 3457a15 converting it into a soft requirement: run
fsck only if supported, leaving otherwise the Artifact unaltered (which
the underlying risk that could be corrupted)

MEN-5082: Restore SSH snapshot feature on Mac OS

---

cli/artifacts.go
cli/sign_test.go

This affects all update module generators.

Fix: signing not working together with `module-image`.

---

cli/artifacts.go
cli/sign_test.go

This affects all update module generators.
(cherry picked from commit 0bc265e8a8c9b799465a58ae342f44ebbd757864)

3.7.x: Fix: signing not working together with `module-image`.

---

cli/read.go

chore(linter): len() of nil maps is defined as zero.

---

areader/reader.go

Reported-by: Johannes Hund <johannes.hund@gmail.com>
Changelog: Fix path seperator to "/". Restores functionality for windows.
Ticket: None

fix: Fix path seperator to "/"

---

.gitlab-ci.yml
Dockerfile
Dockerfile.binaries

As agreed in the client team, we shall stick to the golang version present in the latest release of yocto LTS.

ci: Explicitly set golang version to 1.17

---

cli/write.go

Changelog: `mender-artifact` now detects if the device has an standalone `mender-snapshot`. From Mender client 4.0 onwards, the `mender` binary won't implement `snapshot` command.

MEN-6527 Detect `mender-snapshot` standalone tool

---

.gitlab-ci.yml

This reverts commit 77e1e92f0ebad8dee86a25bba28bf6bf5f930208. The mender-artifact modification is not needed after all, since we decided upon using the already existing debian packages for arm builds

chore: revert add arm64 docker build

---

.gitlab-ci.yml

The previous usage of a default `image` was correct for this repository, but has unfortunately been ported to other repositories where it miss-behaved.
Clean-up a bit the images used by CI with the following ideas:
* For the unit tests, explicitly set the golang version to use
* For non-build jobs, use base Debian images instead of golang ones
* Where possible, use `-slim` versions of the images

QA-639: Explicitly set required `images` per job

---

.gitlab-ci.yml

Previously the pipeline relied on the mender-qa pipeline to finalize the
report after submitting coverage from acceptance tests. However the
coverage from client acceptance tests will be removed soon so we
can already disregard it and make sure we have enough coverage with unit
tests.
See:
* https://github.com/mendersoftware/mender-qa/pull/709

ci: Finalize coverage report from individual pipeline

---

LICENSE
LIC_FILES_CHKSUM.sha256

(cherry picked from commit c00c46a4e4830876d86928f452366dc64ac2b143)

chore: Update license copyright to 2024

---

handlers/module_image.go
handlers/module_image_test.go

changelog: title
ticket: MEN-6199
Signed-off-by: Sebastian Opsahl <sebastian.opsahl@northern.tech>
(cherry picked from commit 7e25d95a9601bef8ed68fd9a408257ba47d980d9)

fix: Unify meta-data element support in mender-artifact and C++ parser, and relax to accept all valid JSON

---

cli/write.go

The path to mender-snapshot was printed when running 'which mender-snapshot'. Now redirecting stdout to /dev/null when checking the path.
Ticket: MEN-7107

chore: omit mender-snapshot path from output

---

Documentation/artifact-format-v3.md

The `|` needs to be escaped to not be confused with table rows delimiter.

docs: Fix formatting in tables

---

cli/util/tty.go

Changelog: Fix an issue with writing Artifact from a remote ssh connection where the user terminal was left with no echo if the `ssh` subprocess exited prematurely.

MEN-7876: Restore tty echo also when cancelling the context

---

.gitlab-ci.yml

Changelog: `mender-artifact` requires now go version 1.22

MEN-8141: Require golang 1.22

---

.gitlab-ci.yml

Historically the publishing of binaries from tags was delegated to
`mender-qa` repository. This was removed some time ago in the context of
switching from binaries to packages but the Mac OS (and Windows)
binaries got lost in the process.
See:
* https://github.com/mendersoftware/mender-qa/commit/67b1b6bcd66af18b5b52814fde30ac3656473f5b
Repurpose the existing CI job here that was publishing the binaries for
branches to take care of the tags too, modernizing a bit the CI spec
along the way.

MEN-8269: Publish Mac OS (and Windows) binaries on Git tags

---

.gitlab-ci.yml

Run the job by setting `INSTALL_BREW` to `true` in gitlab.
Ticket: MEN-8332

ci: add job to install with brew on macos runner 

---

cli/util/ssh.go
cli/write.go

New PR, disregard the old one (701)
Added two separate commits, one for the fix, another for ssh refactoring.
Compared to previous version, I removed fixes for restoring echo and hanging ssh in case remote device fails silently (e.g. power loss). Will move it to new tasks.

Men 8382 mender artifact fails on calling mender update show provides

---

cli/debugfs_test.go
utils/binpath.go

When brew installs binary it will create symlink directory in location like `/usr/local/opt/<binary>/bin`. This location is not part of the system PATH by default.
When mender-artifact evaluates commands location it need to check this brew specific directories apart of default ones.
ticket: MEN-8471
changelog: Extend tools search locations with brew specific ones

chore: Look for binaries in brew specific path

---

.gitlab-ci.yml
Makefile
README.md

In the documentation addressing `build from source` we suggest users to follow
repository instructions for each repo. `mender-artifact` is based on plain Makefile
and when `make` is called without extra parameters build on host will be performed.
In README we suggest to use `make build-natives-contained` as a main build command.
This is not what Makefile is doing by default.
My proposition is to introduce `help` target with displaying some most popular targets,
but not performing any (potential harmful) action by default.
This way user will need to explicite tell `make` what action needs to be performed. 
Ticket: None
Changelog: Add help info to Makefile targets

chore: Add help info when no make target specified

---

cli/util/ssh.go

Ticket: MEN-8429
Changelog: Fix for mender-artifact waiting indefinitely if ssh connection fails silently. Now it drops after 30 seconds.

fix: mender-artifact hangs when ssh connection fails silently
